### ISSUE TITLE
config.yaml parameters

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-demo#1]
Please clarify from where can I get detailed info about parameters mentioned in **config.yaml** ?

**Comment by mverkerk-godaddy** [comment]
Your best bet is the 'common parameters' section in the documentation of the API: https://github.com/godaddy/timings/blob/master/README.md#common-parameters-navtiming-usertiming-and-apitiming

**Comment by vikramvi** [comment]
Thanks for clarification, closing the issue.

**Comment by vikramvi** [comment]
added to https://github.com/Verkurkie/timings-docker/wiki/FAQ-page
