### ISSUE TITLE
Usertiming async test

### ISSUE THREAD

**Issue by dwanedebonocatena** [Verkurkie/timings-demo#2]
Hi

I'm having trouble trying to understand why I cannot get the usertiming async test to work with my example. Basically I copied your js example and changed the url and locators. The demo_start and demo_stop calls are being done, however in the log it only shows that the demo_stop is within the injectCodeReponse.value

I have attached the console log.

[console.log](https://github.com/Verkurkie/timings-demo/files/2068468/console.log)

**Comment by mverkerk-godaddy** [comment]
Hey @dwanedebonocatena - have you tried moving the `performance.mark("demo_start")` up/down in your script? It's weird that `demo_stop` is there but not `demo_start` ... hope it's not something related to wdio ...

**Comment by dwanedebonocatena** [comment]
Hi @Verkurkie , there was actually no issue in the end as in my case I had to use the navtiming rather than the usertiming call since the page document was being reloaded with the click. That is why I was not seeing the demo_start mark. Thank you for replying.
